export const mock = [
  {
    "id": 1,
    "messageId": 1,
    "fileName": "file1.txt",
    "filePath": "/files/file1.txt",
    "fileType": "text",
    "fileSizeBytes": "1234",
    "checksum": "abc123checksum",
    "mimeType": "text/plain",
    "fileOrder": 0,
    "description": "Test file 1",
    "isMetadataFile": false,
    "created_at": "2025-10-24T07:04:40.302Z"
  },
  {
    "id": 3,
    "messageId": 1,
    "fileName": "document.pdf",
    "filePath": "/files/document.pdf",
    "fileType": "pdf",
    "fileSizeBytes": "7890",
    "checksum": "ghi789checksum",
    "mimeType": "application/pdf",
    "fileOrder": 2,
    "description": "Test PDF document",
    "isMetadataFile": false,
    "created_at": "2025-10-24T07:06:09.132Z"
  },
  {
    "id": 5,
    "messageId": 1,
    "fileName": "audio.mp3",
    "filePath": "/files/audio.mp3",
    "fileType": "audio",
    "fileSizeBytes": "5432",
    "checksum": "mno345checksum",
    "mimeType": "audio/mpeg",
    "fileOrder": 4,
    "description": "Test audio file",
    "isMetadataFile": false,
    "created_at": "2025-10-24T07:06:09.132Z"
  },
  {
    "id": 7,
    "messageId": 1,
    "fileName": "archive.zip",
    "filePath": "/files/archive.zip",
    "fileType": "archive",
    "fileSizeBytes": "12345",
    "checksum": "stu901checksum",
    "mimeType": "application/zip",
    "fileOrder": 6,
    "description": "Test archive file",
    "isMetadataFile": false,
    "created_at": "2025-10-24T07:06:09.132Z"
  },
  {
    "id": 8,
    "messageId": 1,
    "fileName": "archive.zip",
    "filePath": "/files/archive.zip",
    "fileType": "archive",
    "fileSizeBytes": "12345",
    "checksum": "stu901checksum",
    "mimeType": "application/zip",
    "fileOrder": 6,
    "description": "Test archive file",
    "isMetadataFile": false,
    "created_at": "2025-10-24T07:06:09.132Z"
  },
  {
    "id": 9,
    "messageId": 1,
    "fileName": "archive.zip",
    "filePath": "/files/archive.zip",
    "fileType": "archive",
    "fileSizeBytes": "12345",
    "checksum": "stu901checksum",
    "mimeType": "application/zip",
    "fileOrder": 6,
    "description": "Test archive file",
    "isMetadataFile": false,
    "created_at": "2025-10-24T07:06:09.132Z"
  },
  {
    "id": 10,
    "messageId": 1,
    "fileName": "archive.zip",
    "filePath": "/files/archive.zip",
    "fileType": "archive",
    "fileSizeBytes": "12345",
    "checksum": "stu901checksum",
    "mimeType": "application/zip",
    "fileOrder": 6,
    "description": "Test archive file",
    "isMetadataFile": false,
    "created_at": "2025-10-24T07:06:09.132Z"
  },
  {
    "id": 11,
    "messageId": 1,
    "fileName": "archive.zip",
    "filePath": "/files/archive.zip",
    "fileType": "archive",
    "fileSizeBytes": "12345",
    "checksum": "stu901checksum",
    "mimeType": "application/zip",
    "fileOrder": 6,
    "description": "Test archive file",
    "isMetadataFile": false,
    "created_at": "2025-10-24T07:06:09.132Z"
  },
  {
    "id": 12,
    "messageId": 1,
    "fileName": "archive.zip",
    "filePath": "/files/archive.zip",
    "fileType": "archive",
    "fileSizeBytes": "12345",
    "checksum": "stu901checksum",
    "mimeType": "application/zip",
    "fileOrder": 6,
    "description": "Test archive file",
    "isMetadataFile": false,
    "created_at": "2025-10-24T07:06:09.132Z"
  },
  {
    "id": 13,
    "messageId": 1,
    "fileName": "archive.zip",
    "filePath": "/files/archive.zip",
    "fileType": "archive",
    "fileSizeBytes": "12345",
    "checksum": "stu901checksum",
    "mimeType": "application/zip",
    "fileOrder": 6,
    "description": "Test archive file",
    "isMetadataFile": false,
    "created_at": "2025-10-24T07:06:09.132Z"
  },
  {
    "id": 14,
    "messageId": 1,
    "fileName": "archive.zip",
    "filePath": "/files/archive.zip",
    "fileType": "archive",
    "fileSizeBytes": "12345",
    "checksum": "stu901checksum",
    "mimeType": "application/zip",
    "fileOrder": 6,
    "description": "Test archive file",
    "isMetadataFile": false,
    "created_at": "2025-10-24T07:06:09.132Z"
  },
  {
    "id": 15,
    "messageId": 1,
    "fileName": "archive.zip",
    "filePath": "/files/archive.zip",
    "fileType": "archive",
    "fileSizeBytes": "12345",
    "checksum": "stu901checksum",
    "mimeType": "application/zip",
    "fileOrder": 6,
    "description": "Test archive file",
    "isMetadataFile": false,
    "created_at": "2025-10-24T07:06:09.132Z"
  },
  {
    "id": 16,
    "messageId": 1,
    "fileName": "archive.zip",
    "filePath": "/files/archive.zip",
    "fileType": "archive",
    "fileSizeBytes": "12345",
    "checksum": "stu901checksum",
    "mimeType": "application/zip",
    "fileOrder": 6,
    "description": "Test archive file",
    "isMetadataFile": false,
    "created_at": "2025-10-24T07:06:09.132Z"
  },
  {
    "id": 17,
    "messageId": 1,
    "fileName": "archive.zip",
    "filePath": "/files/archive.zip",
    "fileType": "archive",
    "fileSizeBytes": "12345",
    "checksum": "stu901checksum",
    "mimeType": "application/zip",
    "fileOrder": 6,
    "description": "Test archive file",
    "isMetadataFile": false,
    "created_at": "2025-10-24T07:06:09.132Z"
  },
  {
    "id": 18,
    "messageId": 1,
    "fileName": "archive.zip",
    "filePath": "/files/archive.zip",
    "fileType": "archive",
    "fileSizeBytes": "12345",
    "checksum": "stu901checksum",
    "mimeType": "application/zip",
    "fileOrder": 6,
    "description": "Test archive file",
    "isMetadataFile": false,
    "created_at": "2025-10-24T07:06:09.132Z"
  },
  {
    "id": 19,
    "messageId": 1,
    "fileName": "archive.zip",
    "filePath": "/files/archive.zip",
    "fileType": "archive",
    "fileSizeBytes": "12345",
    "checksum": "stu901checksum",
    "mimeType": "application/zip",
    "fileOrder": 6,
    "description": "Test archive file",
    "isMetadataFile": false,
    "created_at": "2025-10-24T07:06:09.132Z"
  },
  {
    "id": 20,
    "messageId": 1,
    "fileName": "archive.zip",
    "filePath": "/files/archive.zip",
    "fileType": "archive",
    "fileSizeBytes": "12345",
    "checksum": "stu901checksum",
    "mimeType": "application/zip",
    "fileOrder": 6,
    "description": "Test archive file",
    "isMetadataFile": false,
    "created_at": "2025-10-24T07:06:09.132Z"
  },
]